# Generated by Django 3.2.8 on 2021-10-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('h', 'high'), ('m', 'medium'), ('l', 'low')], default=('m', 'medium'), max_length=1),
        ),
    ]
